# List of lists in the following format:
# ['robot_namespace', 'xbee_address', 'xbee_name']
# For example:
- ['xbee0', '0013A20041CF8FE6', 'STATION_XBEE']
- ['xbee1', '0013A20041CF8F96', 'BOAT_XBEE']

